# Generated by Django 3.2.3 on 2021-08-20 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_reg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reg',
            new_name='Register',
        ),
    ]
