# Generated by Django 3.2.3 on 2021-09-04 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_register_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pname',
            new_name='name',
        ),
    ]
