# Generated by Django 3.2.3 on 2021-09-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210904_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/products/'),
        ),
    ]
