# Generated by Django 3.2.3 on 2021-09-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='description2',
        ),
        migrations.AddField(
            model_name='product',
            name='description1',
            field=models.CharField(default='', max_length=200),
        ),
    ]
