# Generated by Django 3.2.3 on 2021-09-05 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealsOfTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('description1', models.CharField(default='', max_length=200)),
                ('description2', models.CharField(blank=True, max_length=200)),
                ('image1', models.ImageField(upload_to='uploads/products/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='uploads/products/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='uploads/products/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='uploads/products/')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.category')),
            ],
        ),
    ]
