# Generated by Django 3.2.3 on 2021-09-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_dealsoftheday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealsoftheday',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
