# Generated by Django 3.2.3 on 2021-10-11 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20210929_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealsoftheday',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.product'),
        ),
    ]
