# Generated by Django 3.2.3 on 2021-10-11 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_dealsoftheday_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealsoftheday',
            name='category',
        ),
        migrations.RemoveField(
            model_name='dealsoftheday',
            name='description1',
        ),
        migrations.RemoveField(
            model_name='dealsoftheday',
            name='description2',
        ),
        migrations.RemoveField(
            model_name='dealsoftheday',
            name='description3',
        ),
        migrations.RemoveField(
            model_name='dealsoftheday',
            name='description4',
        ),
        migrations.RemoveField(
            model_name='dealsoftheday',
            name='description5',
        ),
        migrations.RemoveField(
            model_name='dealsoftheday',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='dealsoftheday',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='dealsoftheday',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='dealsoftheday',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='dealsoftheday',
            name='name',
        ),
        migrations.RemoveField(
            model_name='dealsoftheday',
            name='offer1',
        ),
        migrations.RemoveField(
            model_name='dealsoftheday',
            name='offer2',
        ),
        migrations.RemoveField(
            model_name='dealsoftheday',
            name='price',
        ),
        migrations.RemoveField(
            model_name='dealsoftheday',
            name='title',
        ),
    ]
